development: &global_setting
  host: localhost
#postgresql
  adapter: postgresql
  encoding: unicode
#mysql
  #adapter: mysql2
  #encoding: utf8
  #reconnect: false
  #socket: /var/run/mysqld/mysqld.sock
  #port: 3306
  database: app_development
  pool: 5
  username: twiquest_user
  password: 123

test:
  database: app_test
  #username: twiquest_user
  #password: kdfmgd3ddgfsd3
  <<: *global_setting

production:
  database: app_production
  #username: twiquest_user
  #password: kdfmgd3ddgfsd3
  <<: *global_setting